# Exercise 2

## Part 1

1. Read the file 'classdata/GameStopTweets.csv' into a pandas dataframe called df. This dataframe contains some tweets that mentioned "#gamestop". The three columns are the screen names of users, the times when the tweets were posted, and the full texts of the tweets.  Show the first five rows.

In [2]:
# Your answer here:
import pandas as pd

df = pd.read_csv('classdata/GameStopTweets.csv')
# Check your answer:
df.head()

,screen_name,created_at,full_text
0,jderiksson,2021-02-01 06:39:58,Is today the day? It could be!\n#stonk #wallst...
1,shadikkandil,2021-02-01 06:39:14,Top 5 Things to Watch in the #US #StockMarkets...
2,thomasschon2,2021-02-01 06:38:59,WSB is what happened that took down the elite ...
3,petervanham,2021-02-01 06:38:46,This article reads more like a personal vendet...
4,Jesse_D_King,2021-02-01 06:38:17,Prophecy from 1999\n#RATM\n#ProphetsOfRage\n#G...

2. Tokenize all tweets and take the following steps to clean the tokens:
    - Turn letters to lower cases.
    - Remove all stop words.
    - Remove all tokens containing no more than 2 characters.
    - Apply stemming to all tokens.
    
  Count the frequencies of all tokens and save the tokens with their frequencies in a data frame called **dffreq**.

In [6]:
# Your answer here:

from collections import Counter              # for word counting
import nltk                                  # for text clearning
import itertools                             # to flatten a list of lists.

stemmer = nltk.stem.SnowballStemmer("english")
global_stopwords = nltk.corpus.stopwords.words("english") 


words_all = [nltk.word_tokenize(s) for s in df["full_text"].str.lower()]
words_all = list(itertools.chain.from_iterable(words_all))
words_all = [s for s in words_all if s not in global_stopwords]
words_all = [s for s in words_all if len(s)>2]
words_all = [stemmer.stem(s) for s in words_all]

counts = Counter(words_all)
dffreq = pd.DataFrame(counts.most_common(), columns=['Term', 'Frequency'])

# Check your answer:
dffreq.head(10)

            Term  Frequency
0       gamestop        573
1          https        361
2            gme        148
3          stock        102
4            amc         92
5  wallstreetbet         72
6      gamestonk         67
7         reddit         67
8      robinhood         62
9         silver         54

3. The following string variable **mystr** contains two phone numbers in the format (xxx) xxx-xxxx. Note that there is a whitespace after ")". Use regular expression that represents a phone number in this format to find all phone numbers in this format in **mystr**. Be careful that "(" and ")" are meta characters and should be escaped.

In [8]:
mystr = "The phone number is (319) 335-0988 not (319) 335-0899"
# Your answer here:
import re
re_phone = '\(\d{3,3}\)\s*\d{3,3}-\d{3,4}'
# Check your answer:
re.findall(re_phone, mystr)

['(319) 335-0988', '(319) 335-0899']

4. The following string variable **tweet_with_url** contains the full text of a tweet in df in question 1. Use regular expression and re.sub to remove all urls in **tweet_with_url** and overwrite **tweet_with_url**. For simplicity, you can assume a url starts with "https://" followed by any number of non-spacing characters.

In [9]:
#Run this cell first
tweet_with_url = df["full_text"][1]
tweet_with_url

'Top 5 Things to Watch in the #US #StockMarkets the Week Ahead - https://t.co/Y1PcautjW9 \n#NASDAQ #GameStop #GameStonk #JobsReport'

In [11]:
# Your answer here:
tweet_with_url = re.sub('https://\S+','',tweet_with_url)
# Check your answer:
tweet_with_url

'Top 5 Things to Watch in the #US #StockMarkets the Week Ahead -  \n#NASDAQ #GameStop #GameStonk #JobsReport'

5. Apply the change made in question 4 to the full text of each tweet in df. Save the result in a new column of df called "full_text_nourl".

In [14]:
# Your answer here:
df['full_text_nourl'] = df['full_text'].str.replace('https://\S+','',regex=True)
# Check your answer:
print(df['full_text'][1])
print(df['full_text_nourl'][1])
df.head()

Top 5 Things to Watch in the #US #StockMarkets the Week Ahead - https://t.co/Y1PcautjW9
#NASDAQ #GameStop #GameStonk #JobsReport
Top 5 Things to Watch in the #US #StockMarkets the Week Ahead -
#NASDAQ #GameStop #GameStonk #JobsReport

,screen_name,created_at,full_text,full_text_nourl
0,jderiksson,2021-02-01 06:39:58,Is today the day? It could be!\n#stonk #wallst...,Is today the day? It could be!\n#stonk #wallst...
1,shadikkandil,2021-02-01 06:39:14,Top 5 Things to Watch in the #US #StockMarkets...,Top 5 Things to Watch in the #US #StockMarkets...
2,thomasschon2,2021-02-01 06:38:59,WSB is what happened that took down the elite ...,WSB is what happened that took down the elite ...
3,petervanham,2021-02-01 06:38:46,This article reads more like a personal vendet...,This article reads more like a personal vendet...
4,Jesse_D_King,2021-02-01 06:38:17,Prophecy from 1999\n#RATM\n#ProphetsOfRage\n#G...,Prophecy from 1999\n#RATM\n#ProphetsOfRage\n#G...

## Part 2

**ipod_onetagV2.txt** contains consumer reviews of ipod. Each line in **ipod_onetagV2.txt** is a sentence from a review and it has the format like **"feature[rating]##text"** where
- **feature** is a keyword (e.g. battery or price) indicating what specific feature of ipod the customer commented about in this sentence. 
- **rating** is a sentiment rating of this review (from -5 to 5) and it is contained in brackets. 
- **text** is the text of the sentence and it is separated from score by double hashtags ##.

The following codes load the data and prints the first five lines.

In [15]:
file = open("classdata/ipod_onetagV2.txt", mode="r")     
textlines = file.readlines()                                  
file.close()                                             
textlines[0:5]

["##Don't get this...keep browsing. \n",
 '##The iPod has so far been one of the most advertised and populated MP3 players so far. \n',
 "##I'm still figuring out why.\n",
 "features[-2]## There isn't much features on the iPod at all, except games.\n",
 "##My friend has this unit while not experience it much, I look at other reviews on this site and tried out the unit at Best Buy, and it's definitely the most overrated gadget in history. \n"]

**Our goal**: Creat three lists called **feature**, **rating**, and **text** that contains each of the three components of each line in **textlines**. There exist some sentences that do not comment on any specific feature. In that case, the line will begin directly with **##text** without the other two components. You must remove those lines first.

1. Use <b>bool(re.search(......))</b> to check whether the first line in **textlines**, textlines[0],  does not begin with "#". Return "True" if it does not begin with "#" and return "False" otherwise. *Hint: what does "^" mean inside square brackets? what does "^" mean outside square brackets?*

In [17]:
#Your answer here
check = [bool(re.search('^[^##]',x)) for x in textlines]
check

[False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

2. Overwrite **textlines** with the lines in **textlines** that do not begin with "#". 

*Hint: You can use list comprehension with if statement. The boolean condition in your if statement can be given by <b>bool(re.search(......))</b>*.

In [18]:
# Your answer here
textlines = [x for x in textlines if bool(re.search('^[^##]',x))]
# Check your answer
textlines[0:5]

["features[-2]## There isn't much features on the iPod at all, except games.\n",
 "sound[2]##SOUND QUALITY: The iPod's sound quality is pretty good.\n",
 'equalizer[-1]## It has an equalizer, but the iRiver H10-20GB has a lot more presets than the iPod. \n',
 'treble[2]##The bass is deep and the treble is clear.\n',
 "battery[-2]##  DURABILITY: Not good. First problem, if you haven't seen the news recently, the iPods are being recalled for battery problems and not lasting the advertised 18 months.\n"]

#### For the purpose of this course, you only need to know how to solve the two questions above. The following three questions are optional, although they can be solved using the RE techniques covered in the lecture. Work on them if you like some challenge.

3. Create a list called **feature** that contains the "feature" component of each line in  **textlines**.

*Hint: You can use list comprehension with <b>re.findall</b> to find the continuous occurrence of letters at the beginning in each line.*

In [21]:
# Your answer here
feature = [re.findall('^[A-Za-z]\w*',x)[0] for x in textlines]
# Check your answer
feature[0:5]

['features', 'sound', 'equalizer', 'treble', 'battery']

4. Create a list called **rating** that contains the "rating" component of each line in  **textlines**.

*Hint: You can use list comprehension with <b>re.findall</b> to find the string pattern like "[...]" in each line. Then you use another  list comprehension with <b>re.sub</b> to remove the square brackets. Be careful that "[" and "]" are meta characters and must be escaped with bachslash.*

In [35]:
# Your answer here
rating = [re.findall('\[.*\]',x)[0] for x in textlines]
rating = [re.sub('[\[\]]','',x) for x in rating]
# Check your answer
rating[0:5]

['-2', '2', '-1', '2', '-2']

5. Create a list called **text** that contains the "text" component of each line in  **textlines**.

*Hint: You can use list comprehension with <b>re.findall</b> to find the string pattern like "##...." in each line. Then you use another list comprehension with <b>re.sub</b> to remove "##". *

In [43]:
# Your answer here
text = [re.findall('##.*',x)[0] for x in textlines]
text = [re.sub('##\s*','',x) for x in text]
# Check your answer
text[0:5]

["There isn't much features on the iPod at all, except games.",
 "SOUND QUALITY: The iPod's sound quality is pretty good.",
 'It has an equalizer, but the iRiver H10-20GB has a lot more presets than the iPod. ',
 'The bass is deep and the treble is clear.',
 "DURABILITY: Not good. First problem, if you haven't seen the news recently, the iPods are being recalled for battery problems and not lasting the advertised 18 months."]