# Preliminary Study

### Summary Statistics

###### Aaron Bromeland

### Needed Imports

In [ ]:
import pandas as pd

### Import Data via CSV

In [17]:
dedf = pd.read_csv("Deere.csv")

### Add Character Lengths to Dataframe

In [18]:
print(len(dedf['text'][0]))
dedf['characters'] = [len(s) for s in dedf['text']]
dedf

4335

,Unnamed: 0,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription,text,characters
0,0,0000315189-22-000016,2022-05-31,2022-05-26,2022-05-31T17:23:01.000Z,NaN,4/A,NaN,NaN,NaN,5012,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4/A\n\n\nSEC Fo...,4335
1,1,0001558370-22-009519,2022-05-31,2022-05-31,2022-05-31T08:35:14.000Z,34.0,8-K,001-04121,22980681.0,"5.02,7.01,9.01",225690,1,1,de-20220531x8k.htm,8-K,\n\n\n\n\n\n0000315189falseDEERE & CO000031518...,6474
2,2,0000315189-22-000015,2022-05-31,2022-05-26,2022-05-31T16:59:24.000Z,NaN,4,NaN,NaN,NaN,33968,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,8053
3,3,0000315189-22-000014,2022-05-31,2022-05-26,2022-05-31T14:43:18.000Z,NaN,4,NaN,NaN,NaN,59067,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,10957
4,4,0001104659-22-065984,2022-05-27,NaN,2022-05-27T16:48:50.000Z,34.0,IRANNOTICE,001-04121,22978525.0,NaN,11971,0,0,tm2217194d1_irannotice.htm,IRANNOTICE,\nIRANNOTICE\n1\ntm2217194d1_irannotice.htm\nI...,1121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,0000315189-11-000041,2011-11-07,2011-09-30,2011-11-07T17:20:44.000Z,34.0,13F-HR,028-00850,111185525.0,NaN,112305,0,0,sep1113f.txt,DEERE & COMPANY 13F-HR,\n13F-HR\n1\nsep1113f.txt\nDEERE & COMPANY 13F...,111082
996,996,0000315189-11-000039,2011-10-03,2011-09-30,2011-10-03T11:12:38.000Z,NaN,4,NaN,NaN,NaN,5674,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,4489
997,997,0000315189-11-000038,2011-10-03,2011-09-30,2011-10-03T10:54:30.000Z,NaN,4,NaN,NaN,NaN,5874,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,4658
998,998,0000315189-11-000037,2011-10-03,2011-09-30,2011-10-03T10:19:03.000Z,NaN,4,NaN,NaN,NaN,5885,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,4703
999,999,0001104659-11-054439,2011-10-03,2011-10-03,2011-10-03T09:00:29.000Z,34.0,8-K,001-04121,111118557.0,7.01,28980,0,0,a11-27268_18k.htm,8-K,\n8-K\n1\na11-27268_18k.htm\n8-K\n\n\n\n\n\n\n...,3517

### Average, Min, Max for current documents

In [19]:
print(f"Average character length: {dedf['characters'].mean()}")
print(f"Minimum character length: {dedf['characters'].min()}")
print(f"Maximum character length: {dedf['characters'].max()}")

Average character length: 24110.144
Minimum character length: 37
Maximum character length: 564539

### Review of small Character Count Documents

In [20]:
dedfSmall = dedf[dedf['characters']<500].copy()
print(dedfSmall.shape)
dedfSmall

(38, 17)

,Unnamed: 0,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription,text,characters
136,136,0000000000-20-010364,2020-11-02,NaN,2020-11-02T16:32:13.000Z,NaN,UPLOAD,NaN,NaN,NaN,39565,0,0,filename1.pdf,NaN,%PDF-1.5\n%����\n1 0 obj\n<>stream\nx����,37
140,140,0000000000-20-009765,2020-10-15,NaN,2020-10-15T17:01:53.000Z,NaN,UPLOAD,NaN,NaN,NaN,42752,0,0,filename1.pdf,NaN,%PDF-1.5\n%����\n1 0 obj\n<>stream\nx����,37
142,142,0000000000-20-009165,2020-09-29,NaN,2020-09-29T17:27:00.000Z,NaN,UPLOAD,NaN,NaN,NaN,43417,0,0,filename1.pdf,NaN,%PDF-1.5\n%����\n1 0 obj\n<>stream\nx����,37
162,162,0000000000-20-003469,2020-04-22,NaN,2020-04-22T17:09:40.000Z,NaN,UPLOAD,NaN,NaN,NaN,39305,0,0,filename1.pdf,NaN,%PDF-1.5\n%����\n1 0 obj\n<>stream\nx����,37
179,179,0000000000-20-001947,2020-03-03,NaN,2020-03-03T17:11:05.000Z,NaN,UPLOAD,NaN,NaN,NaN,49597,0,0,filename1.pdf,NaN,%PDF-1.5\r%����\r\n9 0 obj\r<>\rendobj\r ...,231
227,227,0000000000-19-014171,2019-10-02,NaN,2019-10-02T10:48:15.000Z,NaN,UPLOAD,NaN,NaN,NaN,39177,0,0,filename1.pdf,NaN,%PDF-1.5\r%����\r\n38 0 obj\r<>\rendobj\r ...,283
229,229,0000000000-19-013368,2019-09-10,NaN,2019-09-10T14:53:41.000Z,NaN,UPLOAD,NaN,NaN,NaN,202610,0,0,filename1.pdf,NaN,%PDF-1.5\r%����\r\n64 0 obj\r<>\rendobj\r ...,292
448,448,0000000000-17-003754,2017-02-02,NaN,2017-02-02T15:14:01.000Z,NaN,UPLOAD,NaN,NaN,NaN,41359,0,0,filename1.pdf,NaN,%PDF-1.5\r%����\r\n65 0 obj\r<>\rendobj\r ...,236
491,491,9999999997-17-000003,2016-12-05,2016-10-14,2017-01-03T09:51:33.000Z,34.0,NO ACT,001-04121,16005040.0,NaN,1303,0,0,9999999997-17-000003.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-17-000003.paper\nAUTO-...,220
555,555,9999999997-16-023280,2016-02-25,2015-10-31,2016-05-31T14:30:28.000Z,34.0,11-K,001-04121,16004072.0,NaN,1267,0,0,9999999997-16-023280.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-16-023280.paper\nAUTO-GE...,218
556,556,9999999997-16-023279,2016-02-25,2015-10-31,2016-05-31T14:29:08.000Z,34.0,11-K,001-04121,16004071.0,NaN,1267,0,0,9999999997-16-023279.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-16-023279.paper\nAUTO-GE...,218
558,558,0000000000-16-066018,2016-02-23,NaN,2016-02-23T16:39:18.000Z,NaN,UPLOAD,NaN,NaN,NaN,36020,0,0,filename1.pdf,NaN,%PDF-1.5\r%����\r\n42 0 obj\r<>\rendobj\r ...,241
568,568,0000000000-16-062621,2016-01-27,NaN,2016-01-27T15:59:40.000Z,NaN,UPLOAD,NaN,NaN,NaN,167889,0,0,filename1.pdf,NaN,%PDF-1.5\r%����\r\n117 0 obj\r<>\rendobj\r ...,288
598,598,9999999997-15-015684,2015-12-03,2015-10-05,2015-12-14T15:22:59.000Z,34.0,NO ACT,001-04121,15008364.0,NaN,1303,0,0,9999999997-15-015684.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-15-015684.paper\nAUTO-...,220
661,661,9999999997-15-003501,2015-03-02,2014-10-31,2015-03-12T11:58:18.000Z,34.0,11-K,001-04121,15005489.0,NaN,1267,0,0,9999999997-15-003501.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-15-003501.paper\nAUTO-GE...,218
662,662,9999999997-15-003499,2015-03-02,2014-10-31,2015-03-12T11:56:41.000Z,34.0,11-K,001-04121,15005490.0,NaN,1267,0,0,9999999997-15-003499.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-15-003499.paper\nAUTO-GE...,218
673,673,9999999997-15-000194,2015-01-15,2014-10-31,2015-01-15T13:44:48.000Z,34.0,ARS,001-04121,15005007.0,NaN,1294,0,0,9999999997-15-000194.paper,AUTO-GENERATED PAPER DOCUMENT,\nARS\n1\n9999999997-15-000194.paper\nAUTO-GEN...,217
684,684,9999999997-15-000313,2015-01-05,2014-12-12,2015-01-23T10:22:53.000Z,34.0,NO ACT,001-04121,15005095.0,NaN,1303,0,0,9999999997-15-000313.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-15-000313.paper\nAUTO-...,220
755,755,9999999997-14-001455,2014-03-04,2013-10-31,2014-03-07T11:58:03.000Z,34.0,11-K,001-04121,14005072.0,NaN,1267,0,0,9999999997-14-001455.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-14-001455.paper\nAUTO-GE...,218
756,756,9999999997-14-001452,2014-03-04,2013-10-31,2014-03-07T11:57:25.000Z,34.0,11-K,001-04121,14005073.0,NaN,1267,0,0,9999999997-14-001452.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-14-001452.paper\nAUTO-GE...,218
766,766,9999999997-14-000381,2014-01-14,2013-10-31,2014-01-27T11:15:39.000Z,34.0,ARS,001-04121,13003722.0,NaN,1294,0,0,9999999997-14-000381.paper,AUTO-GENERATED PAPER DOCUMENT,\nARS\n1\n9999999997-14-000381.paper\nAUTO-GEN...,217
800,800,9999999997-13-016602,2013-11-04,2013-09-20,2013-11-13T13:20:15.000Z,34.0,NO ACT,001-04121,13002923.0,NaN,1303,0,0,9999999997-13-016602.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-13-016602.paper\nAUTO-...,220
824,824,0000000000-13-020732,2013-04-17,NaN,2013-04-17T16:06:56.000Z,NaN,UPLOAD,NaN,NaN,NaN,76474,0,0,filename1.pdf,NaN,%PDF-1.5\r%����\r\n46 0 obj\r<>\rendobj\r ...,291
830,830,0000000000-13-016575,2013-03-28,NaN,2013-03-28T13:58:24.000Z,NaN,UPLOAD,NaN,NaN,NaN,201296,0,0,filename1.pdf,NaN,%PDF-1.5\r%����\r\n110 0 obj\r<>\rendobj\r ...,294
843,843,9999999997-13-008515,2013-03-01,2012-10-31,2013-04-22T09:19:19.000Z,34.0,11-K,001-04121,13001677.0,NaN,1267,0,0,9999999997-13-008515.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-13-008515.paper\nAUTO-GE...,218
844,844,9999999997-13-008516,2013-03-01,2012-10-31,2013-04-22T09:22:22.000Z,34.0,11-K,001-04121,13001678.0,NaN,1267,0,0,9999999997-13-008516.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-13-008516.paper\nAUTO-GE...,218
856,856,9999999997-13-000417,2013-01-17,2012-10-31,2013-01-25T14:21:52.000Z,34.0,ARS,001-04121,13000269.0,NaN,1294,0,0,9999999997-13-000417.paper,AUTO-GENERATED PAPER DOCUMENT,\nARS\n1\n9999999997-13-000417.paper\nAUTO-GEN...,217
886,886,9999999997-12-014587,2012-11-13,2012-10-01,2012-11-16T10:35:30.000Z,34.0,NO ACT,001-04121,12028436.0,NaN,1303,0,0,9999999997-12-014587.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-12-014587.paper\nAUTO-...,220
888,888,9999999997-13-008182,2012-10-17,2012-10-17,2013-04-16T11:21:56.000Z,34.0,NO ACT,001-04121,12028603.0,NaN,1303,0,0,9999999997-13-008182.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-13-008182.paper\nAUTO-...,220
893,893,9999999997-12-014135,2012-10-02,2012-10-02,2012-10-15T12:37:52.000Z,34.0,NO ACT,001-04121,12027941.0,NaN,1303,0,0,9999999997-12-014135.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-12-014135.paper\nAUTO-...,220
938,938,9999999997-13-011819,2012-03-02,2011-10-31,2013-07-17T17:11:57.000Z,34.0,11-K,001-04121,13002781.0,NaN,1267,0,0,9999999997-13-011819.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-13-011819.paper\nAUTO-GE...,218
939,939,9999999997-12-002108,2012-03-02,2011-10-31,2012-03-08T10:58:29.000Z,34.0,11-K,001-04121,12025531.0,NaN,1267,0,0,9999999997-12-002108.paper,AUTO-GENERATED PAPER DOCUMENT,\n11-K\n1\n9999999997-12-002108.paper\nAUTO-GE...,218
988,988,9999999997-11-017197,2011-11-18,2011-09-28,2011-12-05T11:54:42.000Z,34.0,NO ACT,001-04121,11008190.0,NaN,1303,0,0,9999999997-11-017197.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-11-017197.paper\nAUTO-...,220
989,989,9999999997-11-017191,2011-11-16,2011-09-16,2011-12-05T11:48:13.000Z,34.0,NO ACT,001-04121,11008184.0,NaN,1303,0,0,9999999997-11-017191.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-11-017191.paper\nAUTO-...,220
991,991,9999999997-11-017190,2011-11-16,2011-09-16,2011-12-05T11:47:13.000Z,34.0,NO ACT,001-04121,11008183.0,NaN,1303,0,0,9999999997-11-017190.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-11-017190.paper\nAUTO-...,220
992,992,9999999997-11-017193,2011-11-16,2011-10-07,2011-12-05T11:50:06.000Z,34.0,NO ACT,001-04121,11008186.0,NaN,1303,0,0,9999999997-11-017193.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-11-017193.paper\nAUTO-...,220
993,993,9999999997-11-017192,2011-11-16,2011-09-16,2011-12-05T11:49:11.000Z,34.0,NO ACT,001-04121,11008185.0,NaN,1303,0,0,9999999997-11-017192.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-11-017192.paper\nAUTO-...,220
994,994,9999999997-11-017194,2011-11-16,2011-09-16,2011-12-05T11:51:00.000Z,34.0,NO ACT,001-04121,11008187.0,NaN,1303,0,0,9999999997-11-017194.paper,AUTO-GENERATED PAPER DOCUMENT,\nNO ACT\n1\n9999999997-11-017194.paper\nAUTO-...,220

In [21]:
dedfSmall['text'][136]

'%PDF-1.5\n%����\n1 0 obj\n<>stream\nx����'

In [22]:
dedfSmall['text'][491]

'\nNO ACT\n1\n9999999997-17-000003.paper\nAUTO-GENERATED PAPER DOCUMENT\n\nThis document was generated as part of a paper submission.\nPlease reference the Document Control Number 16005040 for access to the original document.\n\n\n'

### Remove Small Character Counts and Re-Run Summaries

In [23]:
dedfClean = dedf[dedf['characters']>500].copy()
dedfClean.sort_values(by='filingDate',ascending=False,inplace=True)
dedfClean.reset_index(inplace=True,drop=True)
print(dedfClean.shape)
dedfClean

(962, 17)

,Unnamed: 0,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription,text,characters
0,0,0000315189-22-000016,2022-05-31,2022-05-26,2022-05-31T17:23:01.000Z,NaN,4/A,NaN,NaN,NaN,5012,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4/A\n\n\nSEC Fo...,4335
1,3,0000315189-22-000014,2022-05-31,2022-05-26,2022-05-31T14:43:18.000Z,NaN,4,NaN,NaN,NaN,59067,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,10957
2,1,0001558370-22-009519,2022-05-31,2022-05-31,2022-05-31T08:35:14.000Z,34.0,8-K,001-04121,22980681.0,"5.02,7.01,9.01",225690,1,1,de-20220531x8k.htm,8-K,\n\n\n\n\n\n0000315189falseDEERE & CO000031518...,6474
3,2,0000315189-22-000015,2022-05-31,2022-05-26,2022-05-31T16:59:24.000Z,NaN,4,NaN,NaN,NaN,33968,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,8053
4,4,0001104659-22-065984,2022-05-27,NaN,2022-05-27T16:48:50.000Z,34.0,IRANNOTICE,001-04121,22978525.0,NaN,11971,0,0,tm2217194d1_irannotice.htm,IRANNOTICE,\nIRANNOTICE\n1\ntm2217194d1_irannotice.htm\nI...,1121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,995,0000315189-11-000041,2011-11-07,2011-09-30,2011-11-07T17:20:44.000Z,34.0,13F-HR,028-00850,111185525.0,NaN,112305,0,0,sep1113f.txt,DEERE & COMPANY 13F-HR,\n13F-HR\n1\nsep1113f.txt\nDEERE & COMPANY 13F...,111082
958,996,0000315189-11-000039,2011-10-03,2011-09-30,2011-10-03T11:12:38.000Z,NaN,4,NaN,NaN,NaN,5674,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,4489
959,997,0000315189-11-000038,2011-10-03,2011-09-30,2011-10-03T10:54:30.000Z,NaN,4,NaN,NaN,NaN,5874,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,4658
960,998,0000315189-11-000037,2011-10-03,2011-09-30,2011-10-03T10:19:03.000Z,NaN,4,NaN,NaN,NaN,5885,0,0,xslF345X03/primary_doc.xml,PRIMARY DOCUMENT,\n\n\n\nSEC FORM \n 4\n\n\nSEC Form...,4703
961,999,0001104659-11-054439,2011-10-03,2011-10-03,2011-10-03T09:00:29.000Z,34.0,8-K,001-04121,111118557.0,7.01,28980,0,0,a11-27268_18k.htm,8-K,\n8-K\n1\na11-27268_18k.htm\n8-K\n\n\n\n\n\n\n...,3517

In [25]:
print(f"Average character length: {dedfClean['characters'].mean()}")
print(f"Minimum character length: {dedfClean['characters'].min()}")
print(f"Maximum character length: {dedfClean['characters'].max()}")

Average character length: 25054.20893970894
Minimum character length: 539
Maximum character length: 564539

## Creation of DTM's

### Unigrams

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk
import pysentiment2 as ps

lm = ps.LM()
vectorizer = CountVectorizer(tokenizer = lm.tokenize)
DTM = vectorizer.fit_transform(dedfClean['text'])

In [29]:
dffreq = pd.DataFrame({'Term': vectorizer.get_feature_names_out(),
                   'Frequency': DTM.sum(axis=0).tolist()[0]
                  })

dffreq.sort_values(by="Frequency",inplace=True,ascending=False)
dffreq.reset_index(inplace=True,drop=True)
dffreq.head(10)

/home/abromeland/.local/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

       Term  Frequency
0         s      24071
1     secur      23500
2        on      22773
3   compani      22703
4    report      11962
5      oper      11868
6      form      10900
7  interest      10875
8   financi      10626
9      plan       9874

In [30]:
nltk_stopwords = nltk.corpus.stopwords.words("english")
vectorizer = CountVectorizer(tokenizer = lm.tokenize,stop_words=nltk_stopwords)
DTM = vectorizer.fit_transform(dedfClean['text'])
dffreq = pd.DataFrame({'Term': vectorizer.get_feature_names_out(),
                   'Frequency': DTM.sum(axis=0).tolist()[0]
                  })

dffreq.sort_values(by="Frequency",inplace=True,ascending=False)
dffreq.reset_index(inplace=True,drop=True)
dffreq.head(10)

/home/abromeland/.local/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['onc'] not in stop_words.
  warnings.warn(
/home/abromeland/.local/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

       Term  Frequency
0     secur      23500
1   compani      22703
2    report      11962
3      oper      11868
4      form      10900
5  interest      10875
6   financi      10626
7      plan       9874
8      gaap       9751
9    includ       9490

### Bi-grams

In [33]:
vectorizer = CountVectorizer(tokenizer = lm.tokenize,ngram_range=(2,2))
DTM = vectorizer.fit_transform(dedfClean['text'])
dffreq = pd.DataFrame({'Term': vectorizer.get_feature_names_out(),
                   'Frequency': DTM.sum(axis=0).tolist()[0]
                  })

dffreq.sort_values(by="Frequency",inplace=True,ascending=False)
dffreq.reset_index(inplace=True,drop=True)
dffreq.head(10)

             Term  Frequency
0       compani s       6383
1             u s       5206
2     deriv secur       4541
3      debt secur       4074
4  financi servic       3755
5   secur exchang       3569
6   interest rate       3268
7         base on       2871
8      equip oper       2782
9     exchang act       2761

In [35]:
nltk_stopwords = nltk.corpus.stopwords.words("english")
vectorizer = CountVectorizer(tokenizer = lm.tokenize,stop_words=nltk_stopwords,ngram_range=(2,2))
DTM = vectorizer.fit_transform(dedfClean['text'])
dffreq = pd.DataFrame({'Term': vectorizer.get_feature_names_out(),
                   'Frequency': DTM.sum(axis=0).tolist()[0]
                  })

dffreq.sort_values(by="Frequency",inplace=True,ascending=False)
dffreq.reset_index(inplace=True,drop=True)
dffreq.head(10)

/home/abromeland/.local/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['onc'] not in stop_words.
  warnings.warn(

                Term  Frequency
0        deriv secur       4541
1         debt secur       4074
2     financi servic       3755
3         equip oper       3719
4      secur exchang       3569
5      interest rate       3286
6        exchang act       2761
7       tabl content       2530
8  financi statement       2455
9          incom tax       2382

### Tri-grams

In [36]:
vectorizer = CountVectorizer(tokenizer = lm.tokenize,ngram_range=(3,3))
DTM = vectorizer.fit_transform(dedfClean['text'])
dffreq = pd.DataFrame({'Term': vectorizer.get_feature_names_out(),
                   'Frequency': DTM.sum(axis=0).tolist()[0]
                  })

dffreq.sort_values(by="Frequency",inplace=True,ascending=False)
dffreq.reset_index(inplace=True,drop=True)
dffreq.head(10)

                         Term  Frequency
0         secur acquir dispos       2212
1   prospectu supplement term       1763
2            form file report       1729
3           deriv secur instr       1705
4           secur exchang act       1670
5           instr deriv secur       1659
6          deriv secur acquir       1659
7  consolid financi statement       1318
8      interest rate contract       1293
9                       u s c       1192

In [37]:
nltk_stopwords = nltk.corpus.stopwords.words("english")
vectorizer = CountVectorizer(tokenizer = lm.tokenize,stop_words=nltk_stopwords,ngram_range=(3,3))
DTM = vectorizer.fit_transform(dedfClean['text'])
dffreq = pd.DataFrame({'Term': vectorizer.get_feature_names_out(),
                   'Frequency': DTM.sum(axis=0).tolist()[0]
                  })

dffreq.sort_values(by="Frequency",inplace=True,ascending=False)
dffreq.reset_index(inplace=True,drop=True)
dffreq.head(10)

/home/abromeland/.local/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['onc'] not in stop_words.
  warnings.warn(

                         Term  Frequency
0         secur acquir dispos       2212
1   prospectu supplement term       1763
2            form file report       1729
3           deriv secur instr       1705
4           secur exchang act       1670
5           instr deriv secur       1659
6          deriv secur acquir       1659
7  consolid financi statement       1318
8      interest rate contract       1293
9       direct indirect instr       1152